### ISSUE TITLE
[Bug] removeCompressorRecipe does not work properly

### ISSUE THREAD

**Issue by Mike-U5** [MJRLegends/GalacticraftTweaker#1]
Here's the script I used:
> import mods.GalacticraftTweaker.removeCompressorRecipe;
> removeCompressorRecipe(<galacticraftcore:item_basic_moon:1>);
> removeCompressorRecipe(<galacticraftplanets:item_basic_mars:5>);
> removeCompressorRecipe(<galacticraftplanets:item_basic_asteroids:6>);
> removeCompressorRecipe(<galacticraftcore:heavy_plating>);
> removeCompressorRecipe(<galacticraftplanets:item_basic_mars:3>);
> removeCompressorRecipe(<galacticraftplanets:item_basic_asteroids:5>);

I would expect that this removes the recipes for Compressed Meteoric Iron, Compressed Desh, Compressed Titanium and all 3 tiers of Heavy-Duty Metal.
**Only** Compressed Meteoric Iron is removed, the rest is not. 
No error is placed in the console.

The following mods are installed: 
CraftTweaker2-1.12-4.1.8
GalacticraftCore-1.12.2-4.0.1.177
Galacticraft-Planets-1.12.2-4.0.1.177
GalacticraftTweaker-1.12.2-1.0.1
jei_1.12.2-4.9.1.187
MicdoodleCore-1.12.2-4.0.1.177
modtweaker-4.0.12
MTLib-3.0.5

All of these (except JEI) are required and I am using the latest version at the time of writing.

**Edit:** I tried removing the 
_removeCompressorRecipe(<galacticraftcore:item_basic_moon:1>);_
line to see if it's just the first one that works, but no. It still doesn't remove any of the other recipes.

**Comment by MJRLegends** [comment]
Will take a look but im sure they are shaped recipes or GC dynamic compact recipes which might be the issue

**Comment by MJRLegends** [comment]
@Mike-U5 Please can you confirm the following entries work for me

```
mods.GalacticraftTweaker.addCompressorShapelessRecipe(<galacticraftcore:basic_item:14>,<minecraft:emerald>, null, null, null, null, null, null, null, null);
mods.GalacticraftTweaker.removeCompressorRecipe(<galacticraftcore:basic_item:6>);
```

**Comment by Mike-U5** [comment]
Hey, so sorry for the late reply.
Yes, removing compressed Copper/Tin/Steel/Aluminum/Bronze works fine.
It seems to be specifically compressed Desh, compressed Titanium and Heavy-Duty Metal T1 that I cannot remove.

**Comment by MJRLegends** [comment]
Yeah i think its not possible to change them. I'll take a look if i can solve it.

**Comment by MasterEnderman** [comment]
Just came here to report the same issue. I hope you can fix this. Good luck!

**Comment by MasterEnderman** [comment]
The  following Recipes can't be removed either:
- Heavy-Duty Plate Tier 2
- Heavy-Duty Plate Tier 3

**Comment by MJRLegends** [comment]
Thanks taking a look now, i think i know the issue, might require GC devs input on it but dont worry i will handle that

**Comment by MJRLegends** [comment]
Ok i worked it out you need to put the amount for the item stack of the product your making so for Basic wafer it would be 
`mods.GalacticraftTweaker.removeCompressorRecipe(<galacticraftcore:heavy_plating> * 2);`
not 

`mods.GalacticraftTweaker.removeCompressorRecipe(<galacticraftcore:heavy_plating>);`

You can find these values in JEI 
![d24fcc1f9f157ee4c4e317a75ac67301](https://user-images.githubusercontent.com/8526321/42738971-047809f4-8886-11e8-85d6-4e30ac0e2c87.png)

I've updated the wiki page to say this https://github.com/MJRLegends/GalacticraftTweaker/wiki/CraftTweakerSupport

**Comment by MJRLegends** [comment]
For issues with Tier 2/3 Heavy Plate/ Compressed Titanium and any more that dont work after adding the output amount as explained above for Tier 1 heavy plating, see https://github.com/MJRLegends/GalacticraftTweaker/issues/4
