### ISSUE TITLE
Compressor Recipes not working properly

### ISSUE THREAD

**Issue by xDParis64** [MJRLegends/GalacticraftTweaker#15]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
When I try to delete the 1xmeteroicIronIngot = 1xcompressedMeteroicIron and add 2xmeteroicIronIngot = 1xcompressedMeteroicIron, both recipes get deleted(The deletion comes before I add the new recipe) when I don't remove the recipe both show up

### Steps to Reproduce Issue
1. create this recipe "mods.GalacticraftTweaker.addCompressorShapelessRecipe(<galacticraftcore:item_basic_moon:1>, <galacticraftcore:item_basic_moon>, <galacticraftcore:item_basic_moon>);"
2. Remove this recipe "mods.GalacticraftTweaker.removeCompressorShapelessRecipe(<galacticraftcore:item_basic_moon:1>);"
3. Load the game and neither recipes should work

**Screenshots (if applicable):*
![image](https://user-images.githubusercontent.com/78797641/179837013-cc0039d5-1c24-4151-ba7c-83890c0535a1.png)
![image](https://user-images.githubusercontent.com/78797641/179837057-5a539d76-e103-40a7-94e9-de9ec1ccda2a.png)

Version: 1.12.2-1.0.3

This happened in single player and multiplayer

**Comment by MJRLegends** [comment]
Please can you check if it works with Galacticraft build 280, you can find this at https://micdoodle8.com/mods/galacticraft/downloads, you will need all 3 jars for this build

**Comment by Mathegyl** [comment]
I has the same bug on craftig table with a mod that add two crafts that have the same name.

Try to write two times the remove line

**Comment by MJRLegends** [comment]
>  I has the same bug on craftig table with a mod that add two crafts that have the same name.
> Try to write two times the remove line

Thats a good thought actually, i wonder if thats the problem here.

**Comment by MJRLegends** [comment]
Sorry for the very delayed reply, the recipe is not being removed because `removeCompressorShapelessRecipe `is not a valid craftweaker method provided by GalacticraftTweaker only `removeCompressorRecipe `is
