### ISSUE TITLE
examples page listed on curseforge is a 404

### ISSUE THREAD

**Issue by DougStoker** [MJRLegends/GalacticraftTweaker#17]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Link should be fixed?

If not please let me know

**Comment by MJRLegends** [comment]
Looks like the new beta site is causing issues with links, i will look later when im at my desktop

**Comment by MJRLegends** [comment]
Here is the link if you want for now https://docs.mjrlegends.com/CraftTweaker%20Support/galacticrafttweaker/

**Comment by MJRLegends** [comment]
Seems putting a link with spaces in within the description of a mod listing, when viewing on the new beta website it changes

https://docs.mjrlegends.com/CraftTweaker%20Support/galacticrafttweaker/

https://docs.mjrlegends.com/CraftTweaker+Support/galacticrafttweaker/

Causing issues, so i've just removed the link and added it to the wiki button instead in till curseforge fix their new website
