### ISSUE TITLE
ZenScript NullPointerException error

### ISSUE THREAD

**Issue by NepJr** [MJRLegends/GalacticraftTweaker#19]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
Removing a recipe causes ZenScript to have a null pointer exception

### Steps to Reproduce Issue
1. Remove a recipe using Galacticraft Tweaker
2. That's it

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/5ZuKZ9tx
**Screenshots (if applicable):** 
![image](https://github.com/MJRLegends/GalacticraftTweaker/assets/28848347/d1e8f965-108c-4ae8-acd1-642b955792f6)
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Galacticraft Tweaker 1.12.2-1.0.3
Galacticraft Core & Planets 4.0.5
CraftTweaker2 1.12.2-4.1.20.688
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]
Here's the script: https://pastebin.com/RWYzfy9M

**Comment by MJRLegends** [comment]
Looks like your last line is missing a > at the end of the item name

**Comment by NepJr** [comment]
lol oops
