### ISSUE TITLE
CircuitFabricator issue

### ISSUE THREAD

**Issue by EngineerXL** [MJRLegends/GalacticraftTweaker#5]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Circuit Fabricator recipes can't be added

### Steps to Reproduce Issue
1. Install GalctiCraft Core and Planets, Micdoodle8 Core, GalctiCraft Tweaker, JEI, CraftTweaker.
2. Create script file "Test.zs" 
3. Copy scripts from wiki: https://pastebin.com/x41Xmb9e [This is my script]
4. Launch the game and get error

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/HP6Du5gc

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/37447286/44407372-9cc1e480-a566-11e8-8dda-2a3481e2d58f.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Minecraft 1.12.2; Forge 2757; Galcticraft (Core, Planets, Micdoodle8 core) 181; GalctiCraftTweaker 1.0.1; CraftTweaker 4.1.9;  JEI 4.11.0.212

**Where did this bug happen:** Singleplayer

### Additional Information
It's odd 
![image](https://user-images.githubusercontent.com/37447286/44407910-ebbc4980-a567-11e8-8053-1814527800fd.png)

**Comment by MJRLegends** [comment]
You can ignored what the wiki says read it again and read #3

**Comment by MJRLegends** [comment]
Also update your mods

**Comment by EngineerXL** [comment]
After updating JEI I still getting same error. ALL mods are up to date
![image](https://user-images.githubusercontent.com/37447286/44411928-596c7380-a570-11e8-97f8-ed58dcc92ab7.png)

**Comment by EngineerXL** [comment]
Also I've noticed that it worked only on your MineCraft client 

https://github.com/MJRLegends/GalacticraftTweaker/issues/2

**Comment by MJRLegends** [comment]
#2

**Comment by MJRLegends** [comment]
Fixed version has been uploaded to curseforge sorry about all the hassle 👍 
@EngineerXL
