### ISSUE TITLE
Removing Recipe for T2 Rocket and compressed titanium dont work =(

### ISSUE THREAD

**Issue by Freebi85** [MJRLegends/GalacticraftTweaker#6]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Removing Recipe for T2 Rocket and compressed titanium dont work

### Steps to Reproduce Issue
Simply try to remove the two recipes

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
no crashes.

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** Singelplayer so far

### Additional Information
-

**Comment by MJRLegends** [comment]
Both issues are the same issue of #4

**Comment by EngineerXL** [comment]
Now it works, but T3 rocket doesn't (I've seen issue with compressed desh, heavy-duty plate 2, tier 3 rocket)
![image](https://user-images.githubusercontent.com/37447286/50732632-ed418380-118f-11e9-99b5-68957ae72ee2.png)
![image](https://user-images.githubusercontent.com/37447286/50732636-fb8f9f80-118f-11e9-8b77-61241975c45f.png)

**MJRLegends, is recipe removing for Astro Miner, Cargo Rocket and Buggy planned?**

**Comment by MJRLegends** [comment]
The gc build to fix this isnt out yet and yes i can add support for them

**Comment by MJRLegends** [comment]
Ahh wait it is out. Will give it a check and see where we are with these bugs

**Comment by MJRLegends** [comment]
Ok yes it seems three things are still broken i've made a new issue over with them left over issues at https://github.com/MJRLegends/GalacticraftTweaker/issues/7 if you find anymore broken plz post them. I've also made a pull request for GC to fix this see https://github.com/micdoodle8/Galacticraft/pull/3597
