### ISSUE TITLE
Issues still left with removing GC recipes

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/GalacticraftTweaker#7]
- [x] Issue with not being able to remove Tier 3 Rocket recipe
- [x] Issue with not being able to remove Compressed Desh recipe
- [x] Issue with not being able to remove Heavy-Duty plate 2 recipe

If there is anything else plz post below

**Comment by MJRLegends** [comment]
Pull request has be made for Galacticraft to fix these last 3 issues https://github.com/micdoodle8/Galacticraft/pull/3597

**Comment by EngineerXL** [comment]
186 build is out, thanks for all the work. Also, is it possible to operate with ore gen on asteroids?

**Comment by MJRLegends** [comment]
No problem, also maybe if you join my discord https://discord.gg/SBnvQHc i have channels for each of my mods, your welcome to join and give suggestions for my mods. If you dont have discord your welcome to use the curseforge page for the mod the suggestion is for
