### ISSUE TITLE
[Question] Removing T4-T10 Rockets from Nasa Workbench

### ISSUE THREAD

**Issue by Freebi85** [MJRLegends/GalacticraftTweaker#8]
Hello =)
Is there  a way to remove Extra Planets Rockets (T4-T10) from the Nasa workbench?

**Comment by MJRLegends** [comment]
~~For what MC version?~~ Ahh thought you posted this on ExtraPlanets issue tracker, and they will be away in the next ExtraPlanets version to remove it via CraftTweaker

**Comment by MJRLegends** [comment]
For any more questions, please feel free to ask them on my discord http://discord.mjrlegends.com/
